package com.stefanini.model;
// Generated 07/11/2016 12:03:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Veiculos generated by hbm2java
 */
@Entity
@Table(name = "veiculos", catalog = "hackathon")
public class Veiculos implements java.io.Serializable {

	private String placa;
	private String uf;

	public Veiculos() {
	}

	public Veiculos(String placa, int cpfProprietario, int idModelo, String uf) {
		this.placa = placa;
		this.uf = uf;
	}

	@Id

	@Column(name = "placa", unique = true, nullable = false, length = 7)
	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	@Column(name = "uf", nullable = false, length = 2)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@ManyToOne
	@JoinColumn(name = "cpfProprietario")
	private Proprietario cpfProprietario;

	public Proprietario getCpfProprietario() {
		return cpfProprietario;
	}

	public void setCpfProprietario(Proprietario cpfProprietario) {
		this.cpfProprietario = cpfProprietario;
	}

	public Modelo getIdModelo() {
		return idModelo;
	}

	public void setIdModelo(Modelo idModelo) {
		this.idModelo = idModelo;
	}

	@ManyToOne
	@JoinColumn(name = "idModelo")
	private Modelo idModelo;

}
